### PR TITLE
Added minimally coded html listview. Implemented column order, sorting and grouping. No tests as the code is in flux, not following Java best practices or best Java datastructures etc. No escaping :-0. Basically prototype code.

### PR DESCRIPTION
**Pull request by gabrielh**
Relates to #76

### CODE REVIEW

**Comment by gabrielh** [comment]
The name of the columns must be explicitly specified e.g. : http://localhost:8000/test1?columns=Canton,Commune,Habitants,Wikipedia&orderby=-Habitants,+Canton,-Commune,-Wikipedia&groupby=

**Comment by vorburger** [comment]
Interesting! Thank you very much for this.

Is this a _Draft_ PR (you can mark it as such on GitHub by clicking somehwere) which are you are sharing asking for review feedback on to iterate a bit on, or something you propose for merge as-is?

What strikes me from a first quick review is that this is basically still completely "standalone" - this doesn't "use" the Enola `Entity` proto etc. at all (yet?). Did you mean to do that "integration" in a follow-up? Perhaps that could still be added on this PR before merge?

**Comment by gabrielh** [comment]
Yes, stand-alone for now, I am working on the integration.

**Comment by vorburger** [comment]
Closing as Obsolete, as most of this code touched in this PR has been entirely removed in the mean time.

https://docs.enola.dev/blog/posts/2024-04/ gives an overview of the current state of the project.

**Pull request closed without merging**
